#Schedular
queue: normal
ncpus: 1
walltime: 1:00:00
jobname: TRENDY-S0
storage:
  gdata:
    - rp23

#Model
model: staged_cable
shortpath: /scratch/rp23
input:
  - /g/data/rp23/data/no_provenance/gridinfo
  - /g/data/rp23/data/no_provenance/parameter
  - /g/data/rp23/experiments/2024-03-12_CABLE4-dev/lw5085/payu-demonstration/MetLinks
  - /g/data/rp23/experiments/2024-03-12_CABLE4-dev/lw5085/payu-demonstration/LUC
  - /g/data/rp23/experiments/2024-03-12_CABLE4-dev/lw5085/payu-demonstration/landmasks
exe: /g/data/rp23/experiments/2024-03-12_CABLE4-dev/lw5085/payu-demonstration/bin/cable

restart_freq: 1
